# Generated by Django 5.0 on 2023-12-27 22:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plataform', '0002_rename_patients_patient'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='sex',
            field=models.CharField(choices=[('F', 'Feminino'), ('M', 'Masculino')], max_length=1),
        ),
    ]
