# Generated by Django 5.0 on 2023-12-28 03:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plataform', '0003_alter_patient_sex'),
    ]

    operations = [
        migrations.CreateModel(
            name='DataPatient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateTimeField()),
                ('peso', models.IntegerField()),
                ('altura', models.IntegerField()),
                ('percentual_gordura', models.IntegerField()),
                ('percentual_musculo', models.IntegerField()),
                ('colesterol_hdl', models.IntegerField()),
                ('colesterol_ldl', models.IntegerField()),
                ('colesterol_total', models.IntegerField()),
                ('trigliceridios', models.IntegerField()),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='plataform.patient')),
            ],
        ),
    ]
