# Generated by Django 5.0 on 2023-12-28 05:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('plataform', '0005_rename_paciente_datapatient_patient_snack_option'),
    ]

    operations = [
        migrations.RenameField(
            model_name='snack',
            old_name='paciente',
            new_name='patient',
        ),
    ]
